dataSources:
  ds0: !!org.apache.commons.dbcp.BasicDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ds0
    username: root
    password:
  ds_slave0: !!org.apache.commons.dbcp.BasicDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ds1
    username: root
    password:

masterSlaveRule:
  name: ds_ms
  masterDataSourceName: sd0
  slaveDataSourceNames: [ds1]

  props:
    sql.show: true
  configMap:
    key1: value1